### ISSUE TITLE
Share and Path values

### ISSUE THREAD

**Issue by twmurph** [CarnivalBen/log4net-appender-azurefilestorage#1]
I'm having trouble getting this library to work.  I gotten it to the point where log4net is no longer complaining loading the appender, but it still isn't logging.  I'm wondering if it is the parameters that I'm setting.  Is Share supposed to be the container and Path the folder?  Are both required?

**Comment by CarnivalBen** [comment]
You must specify AzureStorageConnectionString, which you can get from the Azure portal in storage settings, either primary or secondary. It needs to be the full connection string, not just the key.

The ShareName must also be given. It's the name of the share within file storage I which the logs will be created. Example: "logs"

The path can be set to a folder within the share, example: "myapp"

You also need to specify the File, as the file name template.

Check out the README file for examples, this should get you going.
